### ISSUE TITLE
Issue in the Server console

### ISSUE THREAD

**Issue by Taknax** [Tschipp/CallableHorses#15] opened 2022-02-20 21:24 UTC
Everything seems working but i have this in my server console.

[https://pastebin.com/X1LY4P2s](url)

Minecraft: 1.16.5
Forge 36.2.28
CallableHorses: 1.2.1.4

**Comment by ProsperCraft** [comment] 2022-07-27 04:54
Dupe of https://github.com/Tschipp/CallableHorses/issues/14 you can close this issue.

**Closed as completed** 2022-07-27 08:36 UTC
